models:
    - name: team_colors
      description: "Hex color codes for the 351 current men's D1 basketball teams."
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    